name: "org-repo-checks"

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  reposaur_audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Policy Library
        uses: actions/checkout@v3
        with:
          repository: reposaur/policy

      - name: Setup Reposaur
        uses: reposaur/setup-reposaur@main

      - name: Execute Policies
        run: 'rsr exec > report.sarif'
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload Report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: report.sarif
          category: reposaur

  create_summary:
    runs-on: ubuntu-latest
    steps:
      - name: Create job summary
        uses: actions/github-script@v6
        with:
          script: |
            core.summary
              .addHeading('Repository checks on catenax-ng')
              .addTable([
                [
                  {data: 'Repository nane', header: true},
                  {data: 'Has README.md', header: true},
                  {data: 'Has NOTICE.md', header: true},
                  {data: 'Has SECURITY.md', header: true}
                ],
                ['test', ':x:', ':heavy_check_mark:', '	:white_check_mark:'],
              ])
              .addLink('Information on FOSS files!', 'https://github.com/catenax-ng/foss-example#files-from-directory-catenax-ng-repositories')
              .write()
        #run: echo '# Repository checks on catenax-ng' >> $GITHUB_STEP_SUMMARY
